#!/bin/sh
username=$1
password=$2
#export LD_LIBRARY_PATH=/usr/lib/oracle/12.1/client64/lib
sqlplus64 -s "$username/$password@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle12c.cs.torontomu.ca)
(Port=1521))(CONNECT_DATA=(SID=orcl12c)))" <<EOF

DROP TABLE SCHEDULE CASCADE CONSTRAINTS;
DROP TABLE FULL_TIME CASCADE CONSTRAINTS;
DROP TABLE PART_TIME CASCADE CONSTRAINTS;
DROP TABLE BILLING_ADMIN CASCADE CONSTRAINTS;
DROP TABLE DENTAL_STAFF CASCADE CONSTRAINTS;
DROP TABLE SECRETARY CASCADE CONSTRAINTS;
DROP TABLE EMPLOYEE CASCADE CONSTRAINTS;
DROP TABLE FINANCIAL_RECORD CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT_TREATMENT CASCADE CONSTRAINTS;
DROP TABLE TREATMENT CASCADE CONSTRAINTS;
DROP TABLE APPOINTMENT CASCADE CONSTRAINTS;
DROP TABLE PATIENT CASCADE CONSTRAINTS;

exit;
EOF
